Search.appendIndex(
    [
                {
            "fqsen": "\\EM\\Example\\AirportBusTicket",
            "name": "AirportBusTicket",
            "summary": "",
            "url": "classes/EM-Example-AirportBusTicket.html"
        },                {
            "fqsen": "\\EM\\Example\\AirportBusTicket\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/EM-Example-AirportBusTicket.html#method___construct"
        },                {
            "fqsen": "\\EM\\Example\\AirportBusTicket\u003A\u003A\u0024seatNr",
            "name": "seatNr",
            "summary": "",
            "url": "classes/EM-Example-AirportBusTicket.html#property_seatNr"
        },                {
            "fqsen": "\\EM\\Example\\AirportBusTicket\u003A\u003AhumanReadable\u0028\u0029",
            "name": "humanReadable",
            "summary": "",
            "url": "classes/EM-Example-AirportBusTicket.html#method_humanReadable"
        },                {
            "fqsen": "\\EM\\Example\\AirportBusTicket\u003A\u003AgetSeatOutput\u0028\u0029",
            "name": "getSeatOutput",
            "summary": "",
            "url": "classes/EM-Example-AirportBusTicket.html#method_getSeatOutput"
        },                {
            "fqsen": "\\EM\\Example\\AirportBusTicket\u003A\u003AHUMAN_READABLE",
            "name": "HUMAN_READABLE",
            "summary": "",
            "url": "classes/EM-Example-AirportBusTicket.html#constant_HUMAN_READABLE"
        },                {
            "fqsen": "\\EM\\Example\\AirportBusTicket\u003A\u003ASEAT_NUMBER_OUTPUT",
            "name": "SEAT_NUMBER_OUTPUT",
            "summary": "",
            "url": "classes/EM-Example-AirportBusTicket.html#constant_SEAT_NUMBER_OUTPUT"
        },                {
            "fqsen": "\\EM\\Example\\AirportBusTicket\u003A\u003ANO_SEAT_OUTPUT",
            "name": "NO_SEAT_OUTPUT",
            "summary": "",
            "url": "classes/EM-Example-AirportBusTicket.html#constant_NO_SEAT_OUTPUT"
        },                {
            "fqsen": "\\EM\\Example\\AirportTicket",
            "name": "AirportTicket",
            "summary": "",
            "url": "classes/EM-Example-AirportTicket.html"
        },                {
            "fqsen": "\\EM\\Example\\AirportTicket\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/EM-Example-AirportTicket.html#method___construct"
        },                {
            "fqsen": "\\EM\\Example\\AirportTicket\u003A\u003A\u0024ticketNr",
            "name": "ticketNr",
            "summary": "",
            "url": "classes/EM-Example-AirportTicket.html#property_ticketNr"
        },                {
            "fqsen": "\\EM\\Example\\AirportTicket\u003A\u003A\u0024gate",
            "name": "gate",
            "summary": "",
            "url": "classes/EM-Example-AirportTicket.html#property_gate"
        },                {
            "fqsen": "\\EM\\Example\\AirportTicket\u003A\u003A\u0024seat",
            "name": "seat",
            "summary": "",
            "url": "classes/EM-Example-AirportTicket.html#property_seat"
        },                {
            "fqsen": "\\EM\\Example\\AirportTicket\u003A\u003A\u0024luggageType",
            "name": "luggageType",
            "summary": "",
            "url": "classes/EM-Example-AirportTicket.html#property_luggageType"
        },                {
            "fqsen": "\\EM\\Example\\AirportTicket\u003A\u003AhumanReadable\u0028\u0029",
            "name": "humanReadable",
            "summary": "",
            "url": "classes/EM-Example-AirportTicket.html#method_humanReadable"
        },                {
            "fqsen": "\\EM\\Example\\AirportTicket\u003A\u003AHUMAN_READABLE",
            "name": "HUMAN_READABLE",
            "summary": "",
            "url": "classes/EM-Example-AirportTicket.html#constant_HUMAN_READABLE"
        },                {
            "fqsen": "\\EM\\Example\\AirportTicket\u003A\u003ASELF_LUGGAGE_OUTPUT",
            "name": "SELF_LUGGAGE_OUTPUT",
            "summary": "",
            "url": "classes/EM-Example-AirportTicket.html#constant_SELF_LUGGAGE_OUTPUT"
        },                {
            "fqsen": "\\EM\\Example\\AirportTicket\u003A\u003APREVIOUS_FLIGHT_LUGGAGE_OUTPUT",
            "name": "PREVIOUS_FLIGHT_LUGGAGE_OUTPUT",
            "summary": "",
            "url": "classes/EM-Example-AirportTicket.html#constant_PREVIOUS_FLIGHT_LUGGAGE_OUTPUT"
        },                {
            "fqsen": "\\EM\\Example\\AirportTicket\u003A\u003AHUMAN_READABLE_LUGGAGE_OPTIONS",
            "name": "HUMAN_READABLE_LUGGAGE_OPTIONS",
            "summary": "",
            "url": "classes/EM-Example-AirportTicket.html#constant_HUMAN_READABLE_LUGGAGE_OPTIONS"
        },                {
            "fqsen": "\\EM\\Example\\AirportTicket\u003A\u003ASELF_LUGGAGE",
            "name": "SELF_LUGGAGE",
            "summary": "",
            "url": "classes/EM-Example-AirportTicket.html#constant_SELF_LUGGAGE"
        },                {
            "fqsen": "\\EM\\Example\\AirportTicket\u003A\u003ALUGGAGE_PREVIOUS_FLIGHT",
            "name": "LUGGAGE_PREVIOUS_FLIGHT",
            "summary": "",
            "url": "classes/EM-Example-AirportTicket.html#constant_LUGGAGE_PREVIOUS_FLIGHT"
        },                {
            "fqsen": "\\EM\\Example\\AirportTicket\u003A\u003ALUGGAGE_TYPES",
            "name": "LUGGAGE_TYPES",
            "summary": "",
            "url": "classes/EM-Example-AirportTicket.html#constant_LUGGAGE_TYPES"
        },                {
            "fqsen": "\\EM\\Example\\TrainTicket",
            "name": "TrainTicket",
            "summary": "",
            "url": "classes/EM-Example-TrainTicket.html"
        },                {
            "fqsen": "\\EM\\Example\\TrainTicket\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/EM-Example-TrainTicket.html#method___construct"
        },                {
            "fqsen": "\\EM\\Example\\TrainTicket\u003A\u003A\u0024trainNr",
            "name": "trainNr",
            "summary": "",
            "url": "classes/EM-Example-TrainTicket.html#property_trainNr"
        },                {
            "fqsen": "\\EM\\Example\\TrainTicket\u003A\u003A\u0024platform",
            "name": "platform",
            "summary": "",
            "url": "classes/EM-Example-TrainTicket.html#property_platform"
        },                {
            "fqsen": "\\EM\\Example\\TrainTicket\u003A\u003A\u0024seatNr",
            "name": "seatNr",
            "summary": "",
            "url": "classes/EM-Example-TrainTicket.html#property_seatNr"
        },                {
            "fqsen": "\\EM\\Example\\TrainTicket\u003A\u003AhasSeatNr\u0028\u0029",
            "name": "hasSeatNr",
            "summary": "",
            "url": "classes/EM-Example-TrainTicket.html#method_hasSeatNr"
        },                {
            "fqsen": "\\EM\\Example\\TrainTicket\u003A\u003AhumanReadable\u0028\u0029",
            "name": "humanReadable",
            "summary": "",
            "url": "classes/EM-Example-TrainTicket.html#method_humanReadable"
        },                {
            "fqsen": "\\EM\\Example\\TrainTicket\u003A\u003AgetSeatOutput\u0028\u0029",
            "name": "getSeatOutput",
            "summary": "",
            "url": "classes/EM-Example-TrainTicket.html#method_getSeatOutput"
        },                {
            "fqsen": "\\EM\\Example\\TrainTicket\u003A\u003AHUMAN_READABLE",
            "name": "HUMAN_READABLE",
            "summary": "",
            "url": "classes/EM-Example-TrainTicket.html#constant_HUMAN_READABLE"
        },                {
            "fqsen": "\\EM\\Example\\TrainTicket\u003A\u003ASEAT_NUMBER_HR",
            "name": "SEAT_NUMBER_HR",
            "summary": "",
            "url": "classes/EM-Example-TrainTicket.html#constant_SEAT_NUMBER_HR"
        },                {
            "fqsen": "\\EM\\Example\\TrainTicket\u003A\u003ANO_SEAT_HR",
            "name": "NO_SEAT_HR",
            "summary": "",
            "url": "classes/EM-Example-TrainTicket.html#constant_NO_SEAT_HR"
        },                {
            "fqsen": "\\EM\\Example\\TramTicket",
            "name": "TramTicket",
            "summary": "",
            "url": "classes/EM-Example-TramTicket.html"
        },                {
            "fqsen": "\\EM\\Example\\TramTicket\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/EM-Example-TramTicket.html#method___construct"
        },                {
            "fqsen": "\\EM\\Example\\TramTicket\u003A\u003A\u0024ticketNr",
            "name": "ticketNr",
            "summary": "",
            "url": "classes/EM-Example-TramTicket.html#property_ticketNr"
        },                {
            "fqsen": "\\EM\\Example\\TramTicket\u003A\u003AhumanReadable\u0028\u0029",
            "name": "humanReadable",
            "summary": "",
            "url": "classes/EM-Example-TramTicket.html#method_humanReadable"
        },                {
            "fqsen": "\\EM\\Example\\TramTicket\u003A\u003AHUMAN_READABLE",
            "name": "HUMAN_READABLE",
            "summary": "",
            "url": "classes/EM-Example-TramTicket.html#constant_HUMAN_READABLE"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\Algorithm\\TicketSortingAlgorithm",
            "name": "TicketSortingAlgorithm",
            "summary": "",
            "url": "classes/EM-ItineraryManagement-Algorithm-TicketSortingAlgorithm.html"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\Algorithm\\TicketSortingAlgorithm\u003A\u003Asort\u0028\u0029",
            "name": "sort",
            "summary": "",
            "url": "classes/EM-ItineraryManagement-Algorithm-TicketSortingAlgorithm.html#method_sort"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\Algorithm\\TicketSortingAlgorithmA",
            "name": "TicketSortingAlgorithmA",
            "summary": "",
            "url": "classes/EM-ItineraryManagement-Algorithm-TicketSortingAlgorithmA.html"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\Algorithm\\TicketSortingAlgorithmA\u003A\u003Asort\u0028\u0029",
            "name": "sort",
            "summary": "",
            "url": "classes/EM-ItineraryManagement-Algorithm-TicketSortingAlgorithmA.html#method_sort"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\Algorithm\\TicketSortingAlgorithmB",
            "name": "TicketSortingAlgorithmB",
            "summary": "",
            "url": "classes/EM-ItineraryManagement-Algorithm-TicketSortingAlgorithmB.html"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\Algorithm\\TicketSortingAlgorithmB\u003A\u003Asort\u0028\u0029",
            "name": "sort",
            "summary": "",
            "url": "classes/EM-ItineraryManagement-Algorithm-TicketSortingAlgorithmB.html#method_sort"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\Algorithm\\TicketSortingAlgorithmB\u003A\u003AsortB\u0028\u0029",
            "name": "sortB",
            "summary": "",
            "url": "classes/EM-ItineraryManagement-Algorithm-TicketSortingAlgorithmB.html#method_sortB"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\ApplicationService",
            "name": "ApplicationService",
            "summary": "",
            "url": "classes/EM-ItineraryManagement-ApplicationService.html"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\ApplicationService\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/EM-ItineraryManagement-ApplicationService.html#method___construct"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\ApplicationService\u003A\u003Asort\u0028\u0029",
            "name": "sort",
            "summary": "",
            "url": "classes/EM-ItineraryManagement-ApplicationService.html#method_sort"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\ApplicationService\u003A\u003A\u0024sortingAlgorithm",
            "name": "sortingAlgorithm",
            "summary": "",
            "url": "classes/EM-ItineraryManagement-ApplicationService.html#property_sortingAlgorithm"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\Exception\\InvalidArgumentException",
            "name": "InvalidArgumentException",
            "summary": "",
            "url": "classes/EM-ItineraryManagement-Exception-InvalidArgumentException.html"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\Exception\\UnconnectableTicketsException",
            "name": "UnconnectableTicketsException",
            "summary": "",
            "url": "classes/EM-ItineraryManagement-Exception-UnconnectableTicketsException.html"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\ItineraryManager",
            "name": "ItineraryManager",
            "summary": "",
            "url": "classes/EM-ItineraryManagement-ItineraryManager.html"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\ItineraryManager\u003A\u003Asort\u0028\u0029",
            "name": "sort",
            "summary": "",
            "url": "classes/EM-ItineraryManagement-ItineraryManager.html#method_sort"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\Printer",
            "name": "Printer",
            "summary": "",
            "url": "classes/EM-ItineraryManagement-Printer.html"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\Printer\u003A\u003AprintAll\u0028\u0029",
            "name": "printAll",
            "summary": "",
            "url": "classes/EM-ItineraryManagement-Printer.html#method_printAll"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\Ticket\\Printable",
            "name": "Printable",
            "summary": "",
            "url": "classes/EM-ItineraryManagement-Ticket-Printable.html"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\Ticket\\Printable\u003A\u003AhumanReadable\u0028\u0029",
            "name": "humanReadable",
            "summary": "",
            "url": "classes/EM-ItineraryManagement-Ticket-Printable.html#method_humanReadable"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\Ticket\\Ticket",
            "name": "Ticket",
            "summary": "",
            "url": "classes/EM-ItineraryManagement-Ticket-Ticket.html"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\Ticket\\Ticket\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/EM-ItineraryManagement-Ticket-Ticket.html#method___construct"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\Ticket\\Ticket\u003A\u003A\u0024from",
            "name": "from",
            "summary": "",
            "url": "classes/EM-ItineraryManagement-Ticket-Ticket.html#property_from"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\Ticket\\Ticket\u003A\u003A\u0024to",
            "name": "to",
            "summary": "",
            "url": "classes/EM-ItineraryManagement-Ticket-Ticket.html#property_to"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\Ticket\\Ticket\u003A\u003AhumanReadable\u0028\u0029",
            "name": "humanReadable",
            "summary": "",
            "url": "classes/EM-ItineraryManagement-Ticket-Ticket.html#method_humanReadable"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\Ticket\\Tickets",
            "name": "Tickets",
            "summary": "",
            "url": "classes/EM-ItineraryManagement-Ticket-Tickets.html"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\Ticket\\Tickets\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/EM-ItineraryManagement-Ticket-Tickets.html#method___construct"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\Ticket\\Tickets\u003A\u003Acurrent\u0028\u0029",
            "name": "current",
            "summary": "",
            "url": "classes/EM-ItineraryManagement-Ticket-Tickets.html#method_current"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\Ticket\\Tickets\u003A\u003Anext\u0028\u0029",
            "name": "next",
            "summary": "",
            "url": "classes/EM-ItineraryManagement-Ticket-Tickets.html#method_next"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\Ticket\\Tickets\u003A\u003Akey\u0028\u0029",
            "name": "key",
            "summary": "",
            "url": "classes/EM-ItineraryManagement-Ticket-Tickets.html#method_key"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\Ticket\\Tickets\u003A\u003Avalid\u0028\u0029",
            "name": "valid",
            "summary": "",
            "url": "classes/EM-ItineraryManagement-Ticket-Tickets.html#method_valid"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\Ticket\\Tickets\u003A\u003Arewind\u0028\u0029",
            "name": "rewind",
            "summary": "",
            "url": "classes/EM-ItineraryManagement-Ticket-Tickets.html#method_rewind"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\Ticket\\Tickets\u003A\u003A\u0024tickets",
            "name": "tickets",
            "summary": "",
            "url": "classes/EM-ItineraryManagement-Ticket-Tickets.html#property_tickets"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\EM\\Example",
            "name": "Example",
            "summary": "",
            "url": "namespaces/em-example.html"
        },                {
            "fqsen": "\\EM",
            "name": "EM",
            "summary": "",
            "url": "namespaces/em.html"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\Algorithm",
            "name": "Algorithm",
            "summary": "",
            "url": "namespaces/em-itinerarymanagement-algorithm.html"
        },                {
            "fqsen": "\\EM\\ItineraryManagement",
            "name": "ItineraryManagement",
            "summary": "",
            "url": "namespaces/em-itinerarymanagement.html"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "namespaces/em-itinerarymanagement-exception.html"
        },                {
            "fqsen": "\\EM\\ItineraryManagement\\Ticket",
            "name": "Ticket",
            "summary": "",
            "url": "namespaces/em-itinerarymanagement-ticket.html"
        }            ]
);
